Language: generic

Services: 
     - docker

after_success:
    - docker-compose -f docker-compose-build.yaml build --parallel
    - docker tag udagram-api-feed frankywobs/udagram-api-feed:v3
    - docker tag udagram-api-user frankywobs/udagram-api-user:v3
    - docker tag udagram-api-frontend frankywobs/udagram-frontend:v3
    - docker tag reverseproxy frankywobs/reverseproxy:v3
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push frankywobs/udagram-api-feed:v3
    - docker push frankywobs/udagram-api-user:v3
    - docker push frankywobs/udagram-frontend:v3
    - docker push frankywobs/reverseproxy:v3
    