Language: generic

Services: 
     - docker

after_success:
    # Build
    - docker build -t udagram-api-feed ./udagram-api-feed
    - docker build -t udagram-api-user ./udagram-api-user
    - docker build -t udagram-frontend ./udagram-frontend
    - docker build -t udagram-reverseproxy ./reverseproxy
    # Tagging
    - docker tag udagram-api-feed frankywobs/udagram-api-feed:v1
    - docker tag udagram-api-user frankywobs/udagram-api-user:v1
    - docker tag udagram-api-frontend frankywobs/udagram-frontend:v1
    - docker tag udagram-reverseproxy frankywobs/reverseproxy:v1
    #- docker-compose -f docker-compose-build.yaml build --parallel
    # Push
    # Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    # Push
    - docker push frankywobs/udagram-api-feed:v1
    - docker push frankywobs/udagram-api-user:v1
    - docker push frankywobs/udagram-frontend:v1
    - docker push frankywobs/reverseproxy:v1
    